create table if not exists trip_comments (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) <= 40),
  section text not null check (char_length(section) <= 40),
  body text not null check (char_length(body) <= 800),
  created_at timestamptz not null default now()
);

create table if not exists restaurant_votes (
  restaurant_id text not null check (char_length(restaurant_id) <= 60),
  name text not null check (char_length(name) <= 40),
  created_at timestamptz not null default now(),
  primary key (restaurant_id, name)
);

create table if not exists checklist_state (
  item_id text not null check (char_length(item_id) <= 80),
  name text not null check (char_length(name) <= 40),
  done boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key (item_id, name)
);

alter table trip_comments enable row level security;
alter table restaurant_votes enable row level security;
alter table checklist_state enable row level security;

drop policy if exists "Anyone can read trip comments" on trip_comments;
drop policy if exists "Anyone can add trip comments" on trip_comments;
drop policy if exists "Anyone can read restaurant votes" on restaurant_votes;
drop policy if exists "Anyone can add restaurant votes" on restaurant_votes;
drop policy if exists "Anyone can delete restaurant votes" on restaurant_votes;
drop policy if exists "Anyone can read checklist state" on checklist_state;
drop policy if exists "Anyone can add checklist state" on checklist_state;
drop policy if exists "Anyone can update checklist state" on checklist_state;

create policy "Anyone can read trip comments"
on trip_comments for select
to anon
using (true);

create policy "Anyone can add trip comments"
on trip_comments for insert
to anon
with check (true);

create policy "Anyone can read restaurant votes"
on restaurant_votes for select
to anon
using (true);

create policy "Anyone can add restaurant votes"
on restaurant_votes for insert
to anon
with check (true);

create policy "Anyone can delete restaurant votes"
on restaurant_votes for delete
to anon
using (true);

create policy "Anyone can read checklist state"
on checklist_state for select
to anon
using (true);

create policy "Anyone can add checklist state"
on checklist_state for insert
to anon
with check (true);

create policy "Anyone can update checklist state"
on checklist_state for update
to anon
using (true)
with check (true);
